version: "3"
services:
  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   ports:
  #     - 27010:27017
  #   volumes:
  #     - ./data:/data/db
  #   restart: always

  tinywebhook:
    container_name: node-api
    image: allanxq/tinywebhook:latest
    env_file:
      - .env
    ports:
      - 3000:5000
