version: "3"
services:
  mongodb:
    container_name: tinyWebhook-mongodb
    image: mongo:latest
    ports:
      - 27010:27017
    volumes:
      - ./data:/data/db
    restart: always

  tinyWebhook:
    container_name: tinyWebhook
    build: .
    ports:
      - 3000:5000
