name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: list files
        run: ls -la

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tiny_webhook:latest

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VERDANT_PRIVATE_KEY }}

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@"${{ secrets.VERDANT_PUBLIC_IP }}" "mkdir -p tinyWebhook && cd tinyWebhook"
          ssh -o StrictHostKeyChecking=no ubuntu@"${{ secrets.VERDANT_PUBLIC_IP }}" "docker pull ${{ secrets.DOCKER_USERNAME }}/tiny_webhook:latest && docker-compose down && docker-compose up -d"
