name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tiny_webhook:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VERDANT_PRIVATE_KEY }}

      - name: Copy files to AWS EC2
        run: |
          scp -o StrictHostKeyChecking=no Dockerfile ubuntu@${{ secrets.VERDANT_PUBLIC_IP }}:/home/ubuntu/tinyWebhook
          scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.VERDANT_PUBLIC_IP }}:/home/ubuntu/tinyWebhook
          scp -o StrictHostKeyChecking=no .dockerignore ubuntu@${{ secrets.VERDANT_PUBLIC_IP }}:/home/ubuntu/tinyWebhook
          scp -o StrictHostKeyChecking=no package.json ubuntu@${{ secrets.VERDANT_PUBLIC_IP }}:/home/ubuntu/tinyWebhook

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-234-212-0.compute-1.amazonaws.com "echo ${{ secrets.DOCKERHUB_TOKEN }} | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin"
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-234-212-0.compute-1.amazonaws.com "cd tinyWebhook && sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tiny_webhook:latest && sudo docker-compose down && sudo docker-compose up -d"
